=== mmbase/mmbase-taglib/src/org/mmbase/bridge/jsp/taglib/editor/edittagtypes_1_0.dtd
<!ELEMENT   edittagtypes (editor) >
<!ELEMENT   editor  (class,param*,info) >
<!ATTLIST   editor  type    CDATA   #REQUIRED> 
<!ELEMENT   class   (#PCDATA)>
<!ELEMENT   info    (#PCDATA)>

=== mmbase/mmbase-taglib/src/org/mmbase/bridge/jsp/taglib/editor/resources/edittag.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE edittagtypes PUBLIC "-//MMBase//DTD edittagtypes 1.0//EN" "http://www.mmbase.org/dtd/edittagtypes_1_0.dtd">
<edittagtypes>
  <!--
  It is not a good idea to change things in this XML (because this might cause portability issues), but
  you can _add_ (and propose them to the community) or _remove_ things (if you find them undesirable).

  version: $Id: edittag.xml,v 1.1 2005-12-20 09:36:02 andre Exp $
  -->

  <!-- These are the available editors for use with the edittag
  -->
  <editor type="basic">
    <class>org.mmbase.bridge.jsp.taglib.editor.BasicEditor</class>
    <param name="url">/mmbase/edit/basic/change_node.jsp?node_number={NODE.number}</param>
    <info>
      Simple editor, which only searches the base-node and produces a link to the 'basic' editors.
    </info>
  </editor>
  <editor type="my_editors">
    <class>org.mmbase.bridge.jsp.taglib.editor.BasicEditor</class>
    <param name="url">/mmbase/edit/my_editors/edit_object.jsp?nr={NODE.number}</param>
    <info>
      Simple editor, which only searches the base-node and produces a link to 'my_editors'.
    </info>
  </editor>
  <editor type="yammeditor">
    <class>org.mmbase.bridge.jsp.taglib.editor.YAMMEditor</class>
    <info>
      An editor to directly edit content in pages. This is an example 
      implementation which calls the editor yammeditor.jsp.
    </info>
  </editor>


</edittagtypes>
