<?xml version="1.0" encoding="UTF-8" ?>
<!-- DOCTYPE edittagtypes PUBLIC "-//MMBase//DTD edittagtypes 1.0//EN" "http://www.mmbase.org/dtd/edittagtypes_1_0.dtd" -->
<!DOCTYPE   edittagtypes [
<!ELEMENT   edittagtypes (editor+) >
<!ELEMENT   editor  (class*,info*) >
<!ATTLIST   editor  
    type    CDATA   #REQUIRED
> 
<!ELEMENT   class   (#PCDATA)>
<!ELEMENT   info    (#PCDATA)>
]>
<edittagtypes>
  <!--
  It is not a good idea to change things in this XML (because this might cause portability issues), but
  you can _add_ (and propose them to the community) or _remove_ things (if you find them undesirable).

  version: $Id: edittagtypes.xml,v 1.4 2005-12-06 00:02:16 michiel Exp $
  -->

  <!-- These are the available editors for use with the edittag
  -->
  <editor type="basic">
    <class>org.mmbase.bridge.jsp.taglib.editor.BasicEditor</class>
    <param name="url">/mmbase/edit/basic/change_node.jsp?node_number={NODE.number}</param>
    <info>
      Simple editor, which only searched the base-node and produces link to 'basic' editor for it.
    </info>
  </editor>
  <editor type="myeditors">
    <class>org.mmbase.bridge.jsp.taglib.editor.BasicEditor</class>
    <param name="url">/mmbase/edit/my_editors/edit_object.jsp?nr={NODE.number}</param>
    <info>
      Simple editor, which only searched the base-node and produces link to 'my_editors'  for it.
    </info>
  </editor>
  <editor type="yammeditor">
    <class>org.mmbase.bridge.jsp.taglib.editor.YAMMEditor</class>
    <info>
      An editor to directly edit content in pages. This is the example 
      implementation which calls the editor yammeditor.jsp.
    </info>
  </editor>


</edittagtypes>
