=== mmbase/mmbase-taglib/src/org/mmbase/bridge/jsp/taglib/resources/taglibcontent_1_0.dtd
<!ELEMENT taglibcontent (escaper*, postprocessor*) >

<!ELEMENT escaper  (class*) >
<!ATTLIST escaper  id    CDATA  #REQUIRED > 
<!ATTLIST escaper  type  CDATA  #IMPLIED > <!-- type equals id if not speficied -->

<!ELEMENT postprocessor  (class*) >
<!ATTLIST postprocessor  id    CDATA  #REQUIRED > 

<!ELEMENT class      (#PCDATA) >      <!-- class of type CharTransformer -->
<!ATTLIST class  config CDATA  #IMPLIED > 
<!ATTLIST class  back   NMTOKEN  #IMPLIED >   <!-- if 'transformBack' must be used of CharTransformer -->

=== mmbase/mmbase-taglib/src/org/mmbase/bridge/jsp/taglib/resources/taglibcontent.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE taglibcontent PUBLIC "-//MMBase//DTD taglibcontent 1.0//EN" "http://www.mmbase.org/dtd/taglibcontent_1_0.dtd">
<taglibcontent>
  <escaper id="text/plain">
    <class>org.mmbase.util.transformers.CopyCharTransformer</class>
  </escaper>
  <escaper id="none" type="text/html">
    <class>org.mmbase.util.transformers.CopyCharTransformer</class>
  </escaper>
  <escaper id="text/html">
    <class config="ESCAPE">org.mmbase.util.transformers.Xml</class>
  </escaper>
  <escaper id="text/html/attribute" type="text/html">
    <class config="ESCAPE_ATTRIBUTE_HTML">org.mmbase.util.transformers.Xml</class>
  </escaper>
  <escaper id="text/xml">
    <class config="ESCAPE">org.mmbase.util.transformers.Xml</class>
  </escaper>
  <escaper id="text/html/rich" type="text/html">
    <class config="POOR" back="true">org.mmbase.util.transformers.XmlField</class>
  </escaper>

  <postprocessor id="reducespace">
    <class>org.mmbase.util.transformers.SpaceReducer</class>
  </postprocessor>
  <postprocessor id="entities">
    <class>org.mmbase.util.transformers.SpaceReducer</class>
    <class>org.mmbase.util.transformers.XmlEntities</class>
  </postprocessor>
  <postprocessor id="xmetodo">
    <class>org.mmbase.util.transformers.SpaceReducer</class>
    <class config="XMETODO">org.mmbase.util.transformers.Latin3Surrogator</class>
  </postprocessor>
  <postprocessor id="hmetodo">
    <class>org.mmbase.util.transformers.SpaceReducer</class>
    <class config="HMETODO">org.mmbase.util.transformers.Latin3Surrogator</class>
  </postprocessor>
</taglibcontent>
